application: swappass-dot-com
version: 5
runtime: python27
api_version: 1
threadsafe: true


default_expiration: "5m"

builtins:
- remote_api: on


handlers:

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: twistpass.site.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

# For development only
- url: /static/core/
  static_dir: twistpass/core/static/core/
  secure: always

- url: /static/
  static_dir: staticcollected/
  secure: always

# Any URL at /name-that-does-not-contain-a-slash.xyz we can attempt to serve as a static file
# from the /root/ folder.
- url: /([^/]+.(js|css|swf|html|xml|txt|mp3|gif|png|jpg|svg))$
  static_files: root/\1
  upload: /root/.*$
  secure: always

# Allow Let's Encrypt ACME URL to be access on plain HTTP, otherwise renewing certificates after
# they've expired is a pain
- url: /\.well-known/acme-challenge/
  script: twistpass.site.wsgi.application

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: twistpass.site.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: twistpass.site.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - (.*)\.pyc
