application: swappass-dot-com
version: 4
runtime: python27
api_version: 1
threadsafe: true


default_expiration: "5m"

builtins:
- remote_api: on


handlers:

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: swappass.site.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

# For development only
- url: /static/core/
  static_dir: swappass/core/static/core/
  secure: always

- url: /static/
  static_dir: staticcollected/
  secure: always

# robots.txt
- url: /(.+\.(txt))$
  static_files: \1
  upload: /root/.*$


# Allow Let's Encrypt ACME URL to be access on plain HTTP, otherwise renewing certificates after
# they've expired is a pain
- url: /\.well-known/acme-challenge/
  script: swappass.site.wsgi.application

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: swappass.site.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: swappass.site.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - (.*)\.pyc
